version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: sididoc_db
    ports:
      - "${LOCAL_DB_PORT}:5432"
    environment:
        POSTGRES_DB: ${LOCAL_DB_NAME}
        POSTGRES_USER: ${LOCAL_DB_USER}
        POSTGRES_PASSWORD: ${LOCAL_DB_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

volumes:
    pg_data: